[build]
  publish = "Airbnb/frontend/dist"
  command = "cd Airbnb/frontend && npm install && npm run build && cd ../backend && npm install"
  functions = "Airbnb/backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
