[build]
  base = "Airbnb"
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build && cd ../backend && npm install"
  functions = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
